Refactor heisskleber core, remove synchronous implementations
flucto-gmbh/heisskleber pull request #156
Opened 2024-10-10 08:28 UTC by pacjac

This PR includes a significant refactor of our codebase, breaking things along the way.  

Key changes include:

## Code

- Implemented new packer/unpacker interface for more generic usage, being less opinionated about what type of data format to use (I still like dictionaries, but someone else might prefer something with type checking, data classes or lists)
- Improved type hinting and generics usage
- Refactored to fully async implementation, removing synchronous classes
- Added async wrapper for pyserial
- Enhanced AsyncTcpSource with retry and reconnection capabilities
- Renamed various components for consistency

## Repo
- Switched from poetry to uv. We love uv!
- Added nox support for development workflows
- Updated documentation with myst-parser and sphinx

This refactor aims to improve code maintainability, performance, and developer experience.

This PR brings the test coverage down to pretty much 0. Sorry, CoverageBot.

2024-12-04 18:04 UTC, k323r requested changes
Great work! I have a few, small nitpicks here and there, no showstopper, though. Great progress towards v1!

Please review my comments, discard them as you see fit (or incorporate them). Only test_05 from the tcp test suite seems to be broken and I also don't understand it. :shrug:

2024-12-09 14:33 UTC, pacjac commented on src/heisskleber/__init__.py
Added.

2024-12-09 14:33 UTC, pacjac commented on src/heisskleber/console/sink.py
> +        verbose_topic = topic + ":\t" if topic else ""
Changed accordingly.

2024-12-09 14:38 UTC, pacjac commented on src/heisskleber/console/source.py
> +        self.queue: asyncio.Queue[tuple[T, dict[str, Any]]] = asyncio.Queue(maxsize=10)
Typing is dependend on the packer. The ConsoleSource is of type AsyncSource[T]. If I pass it an unpacker of Type dict[str, Any] (which means the unpacker returns a payload of type dict (and an additional meta-dict of type dict)), then the type of the ConsoleSource is [dict[str, Any]].

There is a document on writing your own custom packers and unpackers.

2024-12-09 14:56 UTC, pacjac commented on src/heisskleber/mqtt/sink.py
> +logger = logging.getLogger(__name__)
Done.

2024-12-09 18:30 UTC, k323r approved these changes

2024-12-09 18:32 UTC, merged